apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:PLgUQGU6CFGiaqxQ,iv:yAI94fowETXMoV/tPXL7JtPKCsJF3jvX/GKU8o+xfk0=,tag:ULYRMstkZRSt/9N622M57w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjrf43zt0ggyjhdq07kl7ywdn3gqdtfm30sr9wrrm7l96aav9gpqaay3ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaVExam4vQUo4VkhLVUZm
            eUtNTURXTGludmdOdXZtNmJIZG1OZlUzWlJRCnV3bEF2QmZ2VTQxL3pRNmxnYzBM
            VE1Fd3NmUU4zVU96M1ZmbUR0N3RVVEEKLS0tIDZPcHlnZVZPeVNwYy9iNzE0cUxx
            eVZxeVo0clY4RkUzSVViQnMrdG9uUXcK54q7THeh0dCTg1YeRh8sgGQevNevSpFX
            +S8RVOcd2+YFjPJZMwz/9oQB7fG//jKYvzwdGLkrBCWHGHVu79+yLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T01:58:57Z"
    mac: ENC[AES256_GCM,data:iGiWTKbejJkI5NgMWUTMmEs4LKSGrzXIySmzqjsGbaOW/MKC3nXNfSFZk0WTTXRWvNBALCIBQlg3wQwi56/zfCW5gpbMq5S20m0tn46oLhaGJax/pDDg5fW5O2allv3t97yn7hKkNxaRaph6t1EKpanvAAp0eUNWqbCXzFWR534=,iv:LYn3Sj/PPwyif0KmRTgBt7fLzq0/WjHfS5Y1jUd65b8=,tag:mow3D29+T5cRUAcsncTZ9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
